# Generated by Django 2.2.4 on 2019-08-06 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 12, 40, 45, 334591, tzinfo=utc)),
        ),
    ]
